services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodets-backend-api
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
